name: restaurant_tour
description: Flutter developer coding challenge starter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.19.6"

dependencies:
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.3
  go_router: ^14.8.1
  http: ^1.2.2
  hydrated_bloc: ^10.0.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  path_provider: ^2.1.5
  path_provider_platform_interface: ^2.1.2
  sqflite_common_ffi: ^2.3.3

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.10
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora/Lora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lora/Lora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lora/Lora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lora/Lora-Bold.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
